//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 03:40:27 PM CDT 
//


package com.nibbledebt.intuit.cad.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="accountTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="checking"/>
 *     &lt;enumeration value="savings"/>
 *     &lt;enumeration value="cd"/>
 *     &lt;enumeration value="money market"/>
 *     &lt;enumeration value="recurring deposit"/>
 *     &lt;enumeration value="cash management"/>
 *     &lt;enumeration value="overdraft"/>
 *     &lt;enumeration value="credit card"/>
 *     &lt;enumeration value="line of credit"/>
 *     &lt;enumeration value="taxable investment"/>
 *     &lt;enumeration value="tax-deferred investment"/>
 *     &lt;enumeration value="mortgage"/>
 *     &lt;enumeration value="loan"/>
 *     &lt;enumeration value="annuity"/>
 *     &lt;enumeration value="whole life"/>
 *     &lt;enumeration value="rewards"/>
 *     &lt;enumeration value="email"/>
 *     &lt;enumeration value="biller"/>
 *     &lt;enumeration value="term insurance"/>
 *     &lt;enumeration value="asset"/>
 *     &lt;enumeration value="liability"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "accountTypeEnumeration")
@XmlEnum
public enum AccountTypeEnumeration {

    @XmlEnumValue("checking")
    CHECKING("checking"),
    @XmlEnumValue("savings")
    SAVINGS("savings"),
    @XmlEnumValue("cd")
    CD("cd"),
    @XmlEnumValue("money market")
    MONEY_MARKET("money market"),
    @XmlEnumValue("recurring deposit")
    RECURRING_DEPOSIT("recurring deposit"),
    @XmlEnumValue("cash management")
    CASH_MANAGEMENT("cash management"),
    @XmlEnumValue("overdraft")
    OVERDRAFT("overdraft"),
    @XmlEnumValue("credit card")
    CREDIT_CARD("credit card"),
    @XmlEnumValue("line of credit")
    LINE_OF_CREDIT("line of credit"),
    @XmlEnumValue("taxable investment")
    TAXABLE_INVESTMENT("taxable investment"),
    @XmlEnumValue("tax-deferred investment")
    TAX_DEFERRED_INVESTMENT("tax-deferred investment"),
    @XmlEnumValue("mortgage")
    MORTGAGE("mortgage"),
    @XmlEnumValue("loan")
    LOAN("loan"),
    @XmlEnumValue("annuity")
    ANNUITY("annuity"),
    @XmlEnumValue("whole life")
    WHOLE_LIFE("whole life"),
    @XmlEnumValue("rewards")
    REWARDS("rewards"),
    @XmlEnumValue("email")
    EMAIL("email"),
    @XmlEnumValue("biller")
    BILLER("biller"),
    @XmlEnumValue("term insurance")
    TERM_INSURANCE("term insurance"),
    @XmlEnumValue("asset")
    ASSET("asset"),
    @XmlEnumValue("liability")
    LIABILITY("liability"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    AccountTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccountTypeEnumeration fromValue(String v) {
        for (AccountTypeEnumeration c: AccountTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
