//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 03:39:51 PM CDT 
//


package com.nibbledebt.intuit.cad.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://schema.intuit.com/platform/fdatafeed/bankingaccount/v1}BankingAccount"/>
 *         &lt;element ref="{http://schema.intuit.com/platform/fdatafeed/creditaccount/v1}CreditAccount"/>
 *         &lt;element ref="{http://schema.intuit.com/platform/fdatafeed/loanaccount/v1}LoanAccount"/>
 *         &lt;element ref="{http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1}InvestmentAccount"/>
 *         &lt;element ref="{http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1}RewardsAccount"/>
 *         &lt;element ref="{http://schema.intuit.com/platform/fdatafeed/otheraccount/v1}OtherAccount"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountList", namespace = "http://schema.intuit.com/platform/fdatafeed/accountlist/v1", propOrder = {
    "bankingAccountOrCreditAccountOrLoanAccount"
})
public class AccountList {

    @XmlElements({
        @XmlElement(name = "BankingAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/bankingaccount/v1", type = BankingAccount.class),
        @XmlElement(name = "CreditAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1", type = CreditAccount.class),
        @XmlElement(name = "LoanAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1", type = LoanAccount.class),
        @XmlElement(name = "InvestmentAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1", type = InvestmentAccount.class),
        @XmlElement(name = "RewardsAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1", type = RewardsAccount.class),
        @XmlElement(name = "OtherAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/otheraccount/v1", type = OtherAccount.class)
    })
    protected List<Account> bankingAccountOrCreditAccountOrLoanAccount;

    /**
     * Gets the value of the bankingAccountOrCreditAccountOrLoanAccount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankingAccountOrCreditAccountOrLoanAccount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankingAccountOrCreditAccountOrLoanAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BankingAccount }
     * {@link CreditAccount }
     * {@link LoanAccount }
     * {@link InvestmentAccount }
     * {@link RewardsAccount }
     * {@link OtherAccount }
     * 
     * 
     */
    public List<Account> getBankingAccountOrCreditAccountOrLoanAccount() {
        if (bankingAccountOrCreditAccountOrLoanAccount == null) {
            bankingAccountOrCreditAccountOrLoanAccount = new ArrayList<Account>();
        }
        return this.bankingAccountOrCreditAccountOrLoanAccount;
    }

}
