//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 03:39:51 PM CDT 
//


package com.nibbledebt.intuit.cad.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditAccountType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CreditAccountType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CREDITCARD"/>
 *     &lt;enumeration value="LINEOFCREDIT"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CreditAccountType", namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
@XmlEnum
public enum CreditAccountType {

    CREDITCARD,
    LINEOFCREDIT,
    OTHER;

    public String value() {
        return name();
    }

    public static CreditAccountType fromValue(String v) {
        return valueOf(v);
    }

}
