//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 03:39:51 PM CDT 
//


package com.nibbledebt.intuit.cad.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.intuit.com/platform/fdatafeed/account/v1}Account">
 *       &lt;sequence>
 *         &lt;element name="creditAccountType" type="{http://schema.intuit.com/platform/fdatafeed/creditaccount/v1}CreditAccountType" minOccurs="0"/>
 *         &lt;element name="detailedDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="interestRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="creditAvailableAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="creditMaxAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="cashAdvanceAvailableAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="cashAdvanceMaxAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="cashAdvanceBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="cashAdvanceInterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="currentBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="paymentMinAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="paymentDueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="previousBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="statementEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="statementPurchaseAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="statementFinanceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="pastDueAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="lastPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="lastPaymentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="statementCloseBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="statementLateFeeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creditAccountType",
    "detailedDescription",
    "interestRate",
    "creditAvailableAmount",
    "creditMaxAmount",
    "cashAdvanceAvailableAmount",
    "cashAdvanceMaxAmount",
    "cashAdvanceBalance",
    "cashAdvanceInterestRate",
    "currentBalance",
    "paymentMinAmount",
    "paymentDueDate",
    "previousBalance",
    "statementEndDate",
    "statementPurchaseAmount",
    "statementFinanceAmount",
    "pastDueAmount",
    "lastPaymentAmount",
    "lastPaymentDate",
    "statementCloseBalance",
    "statementLateFeeAmount"
})
@XmlRootElement(name = "CreditAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
public class CreditAccount
    extends Account
{

    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected CreditAccountType creditAccountType;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected String detailedDescription;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal interestRate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal creditAvailableAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal creditMaxAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal cashAdvanceAvailableAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal cashAdvanceMaxAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal cashAdvanceBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal cashAdvanceInterestRate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal currentBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal paymentMinAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar paymentDueDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal previousBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar statementEndDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal statementPurchaseAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal statementFinanceAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal pastDueAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal lastPaymentAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastPaymentDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal statementCloseBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/creditaccount/v1")
    protected BigDecimal statementLateFeeAmount;

    /**
     * Gets the value of the creditAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link CreditAccountType }
     *     
     */
    public CreditAccountType getCreditAccountType() {
        return creditAccountType;
    }

    /**
     * Sets the value of the creditAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditAccountType }
     *     
     */
    public void setCreditAccountType(CreditAccountType value) {
        this.creditAccountType = value;
    }

    /**
     * Gets the value of the detailedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailedDescription() {
        return detailedDescription;
    }

    /**
     * Sets the value of the detailedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailedDescription(String value) {
        this.detailedDescription = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestRate(BigDecimal value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the creditAvailableAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreditAvailableAmount() {
        return creditAvailableAmount;
    }

    /**
     * Sets the value of the creditAvailableAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreditAvailableAmount(BigDecimal value) {
        this.creditAvailableAmount = value;
    }

    /**
     * Gets the value of the creditMaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreditMaxAmount() {
        return creditMaxAmount;
    }

    /**
     * Sets the value of the creditMaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreditMaxAmount(BigDecimal value) {
        this.creditMaxAmount = value;
    }

    /**
     * Gets the value of the cashAdvanceAvailableAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCashAdvanceAvailableAmount() {
        return cashAdvanceAvailableAmount;
    }

    /**
     * Sets the value of the cashAdvanceAvailableAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCashAdvanceAvailableAmount(BigDecimal value) {
        this.cashAdvanceAvailableAmount = value;
    }

    /**
     * Gets the value of the cashAdvanceMaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCashAdvanceMaxAmount() {
        return cashAdvanceMaxAmount;
    }

    /**
     * Sets the value of the cashAdvanceMaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCashAdvanceMaxAmount(BigDecimal value) {
        this.cashAdvanceMaxAmount = value;
    }

    /**
     * Gets the value of the cashAdvanceBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCashAdvanceBalance() {
        return cashAdvanceBalance;
    }

    /**
     * Sets the value of the cashAdvanceBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCashAdvanceBalance(BigDecimal value) {
        this.cashAdvanceBalance = value;
    }

    /**
     * Gets the value of the cashAdvanceInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCashAdvanceInterestRate() {
        return cashAdvanceInterestRate;
    }

    /**
     * Sets the value of the cashAdvanceInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCashAdvanceInterestRate(BigDecimal value) {
        this.cashAdvanceInterestRate = value;
    }

    /**
     * Gets the value of the currentBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentBalance() {
        return currentBalance;
    }

    /**
     * Sets the value of the currentBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentBalance(BigDecimal value) {
        this.currentBalance = value;
    }

    /**
     * Gets the value of the paymentMinAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentMinAmount() {
        return paymentMinAmount;
    }

    /**
     * Sets the value of the paymentMinAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentMinAmount(BigDecimal value) {
        this.paymentMinAmount = value;
    }

    /**
     * Gets the value of the paymentDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDueDate() {
        return paymentDueDate;
    }

    /**
     * Sets the value of the paymentDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentDueDate(XMLGregorianCalendar value) {
        this.paymentDueDate = value;
    }

    /**
     * Gets the value of the previousBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPreviousBalance() {
        return previousBalance;
    }

    /**
     * Sets the value of the previousBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPreviousBalance(BigDecimal value) {
        this.previousBalance = value;
    }

    /**
     * Gets the value of the statementEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStatementEndDate() {
        return statementEndDate;
    }

    /**
     * Sets the value of the statementEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStatementEndDate(XMLGregorianCalendar value) {
        this.statementEndDate = value;
    }

    /**
     * Gets the value of the statementPurchaseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStatementPurchaseAmount() {
        return statementPurchaseAmount;
    }

    /**
     * Sets the value of the statementPurchaseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStatementPurchaseAmount(BigDecimal value) {
        this.statementPurchaseAmount = value;
    }

    /**
     * Gets the value of the statementFinanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStatementFinanceAmount() {
        return statementFinanceAmount;
    }

    /**
     * Sets the value of the statementFinanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStatementFinanceAmount(BigDecimal value) {
        this.statementFinanceAmount = value;
    }

    /**
     * Gets the value of the pastDueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPastDueAmount() {
        return pastDueAmount;
    }

    /**
     * Sets the value of the pastDueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPastDueAmount(BigDecimal value) {
        this.pastDueAmount = value;
    }

    /**
     * Gets the value of the lastPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLastPaymentAmount() {
        return lastPaymentAmount;
    }

    /**
     * Sets the value of the lastPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLastPaymentAmount(BigDecimal value) {
        this.lastPaymentAmount = value;
    }

    /**
     * Gets the value of the lastPaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastPaymentDate() {
        return lastPaymentDate;
    }

    /**
     * Sets the value of the lastPaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastPaymentDate(XMLGregorianCalendar value) {
        this.lastPaymentDate = value;
    }

    /**
     * Gets the value of the statementCloseBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStatementCloseBalance() {
        return statementCloseBalance;
    }

    /**
     * Sets the value of the statementCloseBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStatementCloseBalance(BigDecimal value) {
        this.statementCloseBalance = value;
    }

    /**
     * Gets the value of the statementLateFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStatementLateFeeAmount() {
        return statementLateFeeAmount;
    }

    /**
     * Sets the value of the statementLateFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStatementLateFeeAmount(BigDecimal value) {
        this.statementLateFeeAmount = value;
    }

}
