//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 03:39:51 PM CDT 
//


package com.nibbledebt.intuit.cad.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.intuit.com/platform/fdatafeed/account/v1}Account">
 *       &lt;sequence>
 *         &lt;element name="investmentAccountType" type="{http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1}InvestmentAccountType" minOccurs="0"/>
 *         &lt;element name="interestMarginBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="shortBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="availableCashBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="currentBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="maturityValueAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="unvestedBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="vestedBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="empMatchDeferAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="empMatchDeferAmountYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="empMatchAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="empMatchAmountYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="empPretaxContribAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="empPretaxContribAmountYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="rolloverAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="contribTotalYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="empMatchDeferAmountItd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="empMatchAmountItd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="rolloverItd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="cashBalanceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="initialLoanBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="loanStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="currentLoanBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="loanRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "investmentAccountType",
    "interestMarginBalance",
    "shortBalance",
    "availableCashBalance",
    "currentBalance",
    "maturityValueAmount",
    "unvestedBalance",
    "vestedBalance",
    "empMatchDeferAmount",
    "empMatchDeferAmountYtd",
    "empMatchAmount",
    "empMatchAmountYtd",
    "empPretaxContribAmount",
    "empPretaxContribAmountYtd",
    "rolloverAmount",
    "contribTotalYtd",
    "empMatchDeferAmountItd",
    "empMatchAmountItd",
    "rolloverItd",
    "cashBalanceAmount",
    "initialLoanBalance",
    "loanStartDate",
    "currentLoanBalance",
    "loanRate"
})
@XmlRootElement(name = "InvestmentAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
public class InvestmentAccount
    extends Account
{

    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected String investmentAccountType;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal interestMarginBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal shortBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal availableCashBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal currentBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal maturityValueAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal unvestedBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal vestedBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal empMatchDeferAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal empMatchDeferAmountYtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal empMatchAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal empMatchAmountYtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal empPretaxContribAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal empPretaxContribAmountYtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal rolloverAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal contribTotalYtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal empMatchDeferAmountItd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal empMatchAmountItd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal rolloverItd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal cashBalanceAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal initialLoanBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar loanStartDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal currentLoanBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/investmentaccount/v1")
    protected BigDecimal loanRate;

    /**
     * Gets the value of the investmentAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestmentAccountType() {
        return investmentAccountType;
    }

    /**
     * Sets the value of the investmentAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestmentAccountType(String value) {
        this.investmentAccountType = value;
    }

    /**
     * Gets the value of the interestMarginBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestMarginBalance() {
        return interestMarginBalance;
    }

    /**
     * Sets the value of the interestMarginBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestMarginBalance(BigDecimal value) {
        this.interestMarginBalance = value;
    }

    /**
     * Gets the value of the shortBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getShortBalance() {
        return shortBalance;
    }

    /**
     * Sets the value of the shortBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setShortBalance(BigDecimal value) {
        this.shortBalance = value;
    }

    /**
     * Gets the value of the availableCashBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAvailableCashBalance() {
        return availableCashBalance;
    }

    /**
     * Sets the value of the availableCashBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAvailableCashBalance(BigDecimal value) {
        this.availableCashBalance = value;
    }

    /**
     * Gets the value of the currentBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentBalance() {
        return currentBalance;
    }

    /**
     * Sets the value of the currentBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentBalance(BigDecimal value) {
        this.currentBalance = value;
    }

    /**
     * Gets the value of the maturityValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaturityValueAmount() {
        return maturityValueAmount;
    }

    /**
     * Sets the value of the maturityValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaturityValueAmount(BigDecimal value) {
        this.maturityValueAmount = value;
    }

    /**
     * Gets the value of the unvestedBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnvestedBalance() {
        return unvestedBalance;
    }

    /**
     * Sets the value of the unvestedBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnvestedBalance(BigDecimal value) {
        this.unvestedBalance = value;
    }

    /**
     * Gets the value of the vestedBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVestedBalance() {
        return vestedBalance;
    }

    /**
     * Sets the value of the vestedBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVestedBalance(BigDecimal value) {
        this.vestedBalance = value;
    }

    /**
     * Gets the value of the empMatchDeferAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmpMatchDeferAmount() {
        return empMatchDeferAmount;
    }

    /**
     * Sets the value of the empMatchDeferAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmpMatchDeferAmount(BigDecimal value) {
        this.empMatchDeferAmount = value;
    }

    /**
     * Gets the value of the empMatchDeferAmountYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmpMatchDeferAmountYtd() {
        return empMatchDeferAmountYtd;
    }

    /**
     * Sets the value of the empMatchDeferAmountYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmpMatchDeferAmountYtd(BigDecimal value) {
        this.empMatchDeferAmountYtd = value;
    }

    /**
     * Gets the value of the empMatchAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmpMatchAmount() {
        return empMatchAmount;
    }

    /**
     * Sets the value of the empMatchAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmpMatchAmount(BigDecimal value) {
        this.empMatchAmount = value;
    }

    /**
     * Gets the value of the empMatchAmountYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmpMatchAmountYtd() {
        return empMatchAmountYtd;
    }

    /**
     * Sets the value of the empMatchAmountYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmpMatchAmountYtd(BigDecimal value) {
        this.empMatchAmountYtd = value;
    }

    /**
     * Gets the value of the empPretaxContribAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmpPretaxContribAmount() {
        return empPretaxContribAmount;
    }

    /**
     * Sets the value of the empPretaxContribAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmpPretaxContribAmount(BigDecimal value) {
        this.empPretaxContribAmount = value;
    }

    /**
     * Gets the value of the empPretaxContribAmountYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmpPretaxContribAmountYtd() {
        return empPretaxContribAmountYtd;
    }

    /**
     * Sets the value of the empPretaxContribAmountYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmpPretaxContribAmountYtd(BigDecimal value) {
        this.empPretaxContribAmountYtd = value;
    }

    /**
     * Gets the value of the rolloverAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRolloverAmount() {
        return rolloverAmount;
    }

    /**
     * Sets the value of the rolloverAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRolloverAmount(BigDecimal value) {
        this.rolloverAmount = value;
    }

    /**
     * Gets the value of the contribTotalYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getContribTotalYtd() {
        return contribTotalYtd;
    }

    /**
     * Sets the value of the contribTotalYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setContribTotalYtd(BigDecimal value) {
        this.contribTotalYtd = value;
    }

    /**
     * Gets the value of the empMatchDeferAmountItd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmpMatchDeferAmountItd() {
        return empMatchDeferAmountItd;
    }

    /**
     * Sets the value of the empMatchDeferAmountItd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmpMatchDeferAmountItd(BigDecimal value) {
        this.empMatchDeferAmountItd = value;
    }

    /**
     * Gets the value of the empMatchAmountItd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmpMatchAmountItd() {
        return empMatchAmountItd;
    }

    /**
     * Sets the value of the empMatchAmountItd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmpMatchAmountItd(BigDecimal value) {
        this.empMatchAmountItd = value;
    }

    /**
     * Gets the value of the rolloverItd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRolloverItd() {
        return rolloverItd;
    }

    /**
     * Sets the value of the rolloverItd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRolloverItd(BigDecimal value) {
        this.rolloverItd = value;
    }

    /**
     * Gets the value of the cashBalanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCashBalanceAmount() {
        return cashBalanceAmount;
    }

    /**
     * Sets the value of the cashBalanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCashBalanceAmount(BigDecimal value) {
        this.cashBalanceAmount = value;
    }

    /**
     * Gets the value of the initialLoanBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInitialLoanBalance() {
        return initialLoanBalance;
    }

    /**
     * Sets the value of the initialLoanBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInitialLoanBalance(BigDecimal value) {
        this.initialLoanBalance = value;
    }

    /**
     * Gets the value of the loanStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLoanStartDate() {
        return loanStartDate;
    }

    /**
     * Sets the value of the loanStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLoanStartDate(XMLGregorianCalendar value) {
        this.loanStartDate = value;
    }

    /**
     * Gets the value of the currentLoanBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentLoanBalance() {
        return currentLoanBalance;
    }

    /**
     * Sets the value of the currentLoanBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentLoanBalance(BigDecimal value) {
        this.currentLoanBalance = value;
    }

    /**
     * Gets the value of the loanRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoanRate() {
        return loanRate;
    }

    /**
     * Sets the value of the loanRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoanRate(BigDecimal value) {
        this.loanRate = value;
    }

}
