//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 03:39:51 PM CDT 
//


package com.nibbledebt.intuit.cad.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.intuit.com/platform/fdatafeed/account/v1}Account">
 *       &lt;sequence>
 *         &lt;element name="loanDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loanType" type="{http://schema.intuit.com/platform/fdatafeed/loanaccount/v1}LoanType" minOccurs="0"/>
 *         &lt;element name="postedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="holderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lateFeeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="payoffAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="payoffAmountDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="referenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originalMaturityDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="taxPayeeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="principalBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="escrowBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="interestRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="interestPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="initialAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="initialDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="nextPaymentPrincipalAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="nextPaymentInterestAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="nextPayment" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="nextPaymentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lastPaymentDueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lastPaymentReceiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lastPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="lastPaymentPrincipalAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="lastPaymentInterestAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="lastPaymentEscrowAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="lastPaymentLastFeeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="lastPaymentLateCharge" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="principalPaidYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="interestPaidYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="insurancePaidYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="taxPaidYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="autopayEnrolled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="collateral" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currentSchool" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="firstPaymentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="guarantor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="firstMortgage" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="loanPaymentFreq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="paymentMinAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="originalSchool" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recurringPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="lender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="endingBalanceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="availableBalanceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="loanTermType" type="{http://schema.intuit.com/platform/fdatafeed/loanaccount/v1}LoanTermType" minOccurs="0"/>
 *         &lt;element name="noOfPayments" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="balloonAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="projectedInterest" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="interestPaidLtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="interestRateType" type="{http://schema.intuit.com/platform/fdatafeed/loanaccount/v1}RateType" minOccurs="0"/>
 *         &lt;element name="loanPaymentType" type="{http://schema.intuit.com/platform/fdatafeed/loanaccount/v1}PaymentType" minOccurs="0"/>
 *         &lt;element name="remainingPayments" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "loanDescription",
    "loanType",
    "postedDate",
    "term",
    "holderName",
    "lateFeeAmount",
    "payoffAmount",
    "payoffAmountDate",
    "referenceNumber",
    "originalMaturityDate",
    "taxPayeeName",
    "principalBalance",
    "escrowBalance",
    "interestRate",
    "interestPeriod",
    "initialAmount",
    "initialDate",
    "nextPaymentPrincipalAmount",
    "nextPaymentInterestAmount",
    "nextPayment",
    "nextPaymentDate",
    "lastPaymentDueDate",
    "lastPaymentReceiveDate",
    "lastPaymentAmount",
    "lastPaymentPrincipalAmount",
    "lastPaymentInterestAmount",
    "lastPaymentEscrowAmount",
    "lastPaymentLastFeeAmount",
    "lastPaymentLateCharge",
    "principalPaidYtd",
    "interestPaidYtd",
    "insurancePaidYtd",
    "taxPaidYtd",
    "autopayEnrolled",
    "collateral",
    "currentSchool",
    "firstPaymentDate",
    "guarantor",
    "firstMortgage",
    "loanPaymentFreq",
    "paymentMinAmount",
    "originalSchool",
    "recurringPaymentAmount",
    "lender",
    "endingBalanceAmount",
    "availableBalanceAmount",
    "loanTermType",
    "noOfPayments",
    "balloonAmount",
    "projectedInterest",
    "interestPaidLtd",
    "interestRateType",
    "loanPaymentType",
    "remainingPayments"
})
@XmlRootElement(name = "LoanAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
public class LoanAccount
    extends Account
{

    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String loanDescription;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected LoanType loanType;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar postedDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String term;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String holderName;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal lateFeeAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal payoffAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar payoffAmountDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String referenceNumber;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar originalMaturityDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String taxPayeeName;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal principalBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal escrowBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal interestRate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String interestPeriod;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal initialAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar initialDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal nextPaymentPrincipalAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal nextPaymentInterestAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal nextPayment;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar nextPaymentDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastPaymentDueDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastPaymentReceiveDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal lastPaymentAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal lastPaymentPrincipalAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal lastPaymentInterestAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal lastPaymentEscrowAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal lastPaymentLastFeeAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal lastPaymentLateCharge;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal principalPaidYtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal interestPaidYtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal insurancePaidYtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal taxPaidYtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected Boolean autopayEnrolled;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String collateral;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String currentSchool;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar firstPaymentDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String guarantor;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected Boolean firstMortgage;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String loanPaymentFreq;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal paymentMinAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String originalSchool;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal recurringPaymentAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected String lender;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal endingBalanceAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal availableBalanceAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected LoanTermType loanTermType;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected Integer noOfPayments;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal balloonAmount;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal projectedInterest;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected BigDecimal interestPaidLtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected RateType interestRateType;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected PaymentType loanPaymentType;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
    protected Integer remainingPayments;

    /**
     * Gets the value of the loanDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanDescription() {
        return loanDescription;
    }

    /**
     * Sets the value of the loanDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanDescription(String value) {
        this.loanDescription = value;
    }

    /**
     * Gets the value of the loanType property.
     * 
     * @return
     *     possible object is
     *     {@link LoanType }
     *     
     */
    public LoanType getLoanType() {
        return loanType;
    }

    /**
     * Sets the value of the loanType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanType }
     *     
     */
    public void setLoanType(LoanType value) {
        this.loanType = value;
    }

    /**
     * Gets the value of the postedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostedDate() {
        return postedDate;
    }

    /**
     * Sets the value of the postedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPostedDate(XMLGregorianCalendar value) {
        this.postedDate = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the holderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHolderName() {
        return holderName;
    }

    /**
     * Sets the value of the holderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHolderName(String value) {
        this.holderName = value;
    }

    /**
     * Gets the value of the lateFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLateFeeAmount() {
        return lateFeeAmount;
    }

    /**
     * Sets the value of the lateFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLateFeeAmount(BigDecimal value) {
        this.lateFeeAmount = value;
    }

    /**
     * Gets the value of the payoffAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPayoffAmount() {
        return payoffAmount;
    }

    /**
     * Sets the value of the payoffAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPayoffAmount(BigDecimal value) {
        this.payoffAmount = value;
    }

    /**
     * Gets the value of the payoffAmountDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPayoffAmountDate() {
        return payoffAmountDate;
    }

    /**
     * Sets the value of the payoffAmountDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPayoffAmountDate(XMLGregorianCalendar value) {
        this.payoffAmountDate = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNumber(String value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the originalMaturityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOriginalMaturityDate() {
        return originalMaturityDate;
    }

    /**
     * Sets the value of the originalMaturityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOriginalMaturityDate(XMLGregorianCalendar value) {
        this.originalMaturityDate = value;
    }

    /**
     * Gets the value of the taxPayeeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxPayeeName() {
        return taxPayeeName;
    }

    /**
     * Sets the value of the taxPayeeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxPayeeName(String value) {
        this.taxPayeeName = value;
    }

    /**
     * Gets the value of the principalBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrincipalBalance() {
        return principalBalance;
    }

    /**
     * Sets the value of the principalBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrincipalBalance(BigDecimal value) {
        this.principalBalance = value;
    }

    /**
     * Gets the value of the escrowBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEscrowBalance() {
        return escrowBalance;
    }

    /**
     * Sets the value of the escrowBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEscrowBalance(BigDecimal value) {
        this.escrowBalance = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestRate(BigDecimal value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the interestPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestPeriod() {
        return interestPeriod;
    }

    /**
     * Sets the value of the interestPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestPeriod(String value) {
        this.interestPeriod = value;
    }

    /**
     * Gets the value of the initialAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInitialAmount() {
        return initialAmount;
    }

    /**
     * Sets the value of the initialAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInitialAmount(BigDecimal value) {
        this.initialAmount = value;
    }

    /**
     * Gets the value of the initialDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInitialDate() {
        return initialDate;
    }

    /**
     * Sets the value of the initialDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInitialDate(XMLGregorianCalendar value) {
        this.initialDate = value;
    }

    /**
     * Gets the value of the nextPaymentPrincipalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextPaymentPrincipalAmount() {
        return nextPaymentPrincipalAmount;
    }

    /**
     * Sets the value of the nextPaymentPrincipalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextPaymentPrincipalAmount(BigDecimal value) {
        this.nextPaymentPrincipalAmount = value;
    }

    /**
     * Gets the value of the nextPaymentInterestAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextPaymentInterestAmount() {
        return nextPaymentInterestAmount;
    }

    /**
     * Sets the value of the nextPaymentInterestAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextPaymentInterestAmount(BigDecimal value) {
        this.nextPaymentInterestAmount = value;
    }

    /**
     * Gets the value of the nextPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextPayment() {
        return nextPayment;
    }

    /**
     * Sets the value of the nextPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextPayment(BigDecimal value) {
        this.nextPayment = value;
    }

    /**
     * Gets the value of the nextPaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNextPaymentDate() {
        return nextPaymentDate;
    }

    /**
     * Sets the value of the nextPaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNextPaymentDate(XMLGregorianCalendar value) {
        this.nextPaymentDate = value;
    }

    /**
     * Gets the value of the lastPaymentDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastPaymentDueDate() {
        return lastPaymentDueDate;
    }

    /**
     * Sets the value of the lastPaymentDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastPaymentDueDate(XMLGregorianCalendar value) {
        this.lastPaymentDueDate = value;
    }

    /**
     * Gets the value of the lastPaymentReceiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastPaymentReceiveDate() {
        return lastPaymentReceiveDate;
    }

    /**
     * Sets the value of the lastPaymentReceiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastPaymentReceiveDate(XMLGregorianCalendar value) {
        this.lastPaymentReceiveDate = value;
    }

    /**
     * Gets the value of the lastPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLastPaymentAmount() {
        return lastPaymentAmount;
    }

    /**
     * Sets the value of the lastPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLastPaymentAmount(BigDecimal value) {
        this.lastPaymentAmount = value;
    }

    /**
     * Gets the value of the lastPaymentPrincipalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLastPaymentPrincipalAmount() {
        return lastPaymentPrincipalAmount;
    }

    /**
     * Sets the value of the lastPaymentPrincipalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLastPaymentPrincipalAmount(BigDecimal value) {
        this.lastPaymentPrincipalAmount = value;
    }

    /**
     * Gets the value of the lastPaymentInterestAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLastPaymentInterestAmount() {
        return lastPaymentInterestAmount;
    }

    /**
     * Sets the value of the lastPaymentInterestAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLastPaymentInterestAmount(BigDecimal value) {
        this.lastPaymentInterestAmount = value;
    }

    /**
     * Gets the value of the lastPaymentEscrowAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLastPaymentEscrowAmount() {
        return lastPaymentEscrowAmount;
    }

    /**
     * Sets the value of the lastPaymentEscrowAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLastPaymentEscrowAmount(BigDecimal value) {
        this.lastPaymentEscrowAmount = value;
    }

    /**
     * Gets the value of the lastPaymentLastFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLastPaymentLastFeeAmount() {
        return lastPaymentLastFeeAmount;
    }

    /**
     * Sets the value of the lastPaymentLastFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLastPaymentLastFeeAmount(BigDecimal value) {
        this.lastPaymentLastFeeAmount = value;
    }

    /**
     * Gets the value of the lastPaymentLateCharge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLastPaymentLateCharge() {
        return lastPaymentLateCharge;
    }

    /**
     * Sets the value of the lastPaymentLateCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLastPaymentLateCharge(BigDecimal value) {
        this.lastPaymentLateCharge = value;
    }

    /**
     * Gets the value of the principalPaidYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrincipalPaidYtd() {
        return principalPaidYtd;
    }

    /**
     * Sets the value of the principalPaidYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrincipalPaidYtd(BigDecimal value) {
        this.principalPaidYtd = value;
    }

    /**
     * Gets the value of the interestPaidYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestPaidYtd() {
        return interestPaidYtd;
    }

    /**
     * Sets the value of the interestPaidYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestPaidYtd(BigDecimal value) {
        this.interestPaidYtd = value;
    }

    /**
     * Gets the value of the insurancePaidYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInsurancePaidYtd() {
        return insurancePaidYtd;
    }

    /**
     * Sets the value of the insurancePaidYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInsurancePaidYtd(BigDecimal value) {
        this.insurancePaidYtd = value;
    }

    /**
     * Gets the value of the taxPaidYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxPaidYtd() {
        return taxPaidYtd;
    }

    /**
     * Sets the value of the taxPaidYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxPaidYtd(BigDecimal value) {
        this.taxPaidYtd = value;
    }

    /**
     * Gets the value of the autopayEnrolled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutopayEnrolled() {
        return autopayEnrolled;
    }

    /**
     * Sets the value of the autopayEnrolled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutopayEnrolled(Boolean value) {
        this.autopayEnrolled = value;
    }

    /**
     * Gets the value of the collateral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollateral() {
        return collateral;
    }

    /**
     * Sets the value of the collateral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollateral(String value) {
        this.collateral = value;
    }

    /**
     * Gets the value of the currentSchool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentSchool() {
        return currentSchool;
    }

    /**
     * Sets the value of the currentSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentSchool(String value) {
        this.currentSchool = value;
    }

    /**
     * Gets the value of the firstPaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstPaymentDate() {
        return firstPaymentDate;
    }

    /**
     * Sets the value of the firstPaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstPaymentDate(XMLGregorianCalendar value) {
        this.firstPaymentDate = value;
    }

    /**
     * Gets the value of the guarantor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuarantor() {
        return guarantor;
    }

    /**
     * Sets the value of the guarantor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuarantor(String value) {
        this.guarantor = value;
    }

    /**
     * Gets the value of the firstMortgage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFirstMortgage() {
        return firstMortgage;
    }

    /**
     * Sets the value of the firstMortgage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFirstMortgage(Boolean value) {
        this.firstMortgage = value;
    }

    /**
     * Gets the value of the loanPaymentFreq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanPaymentFreq() {
        return loanPaymentFreq;
    }

    /**
     * Sets the value of the loanPaymentFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanPaymentFreq(String value) {
        this.loanPaymentFreq = value;
    }

    /**
     * Gets the value of the paymentMinAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentMinAmount() {
        return paymentMinAmount;
    }

    /**
     * Sets the value of the paymentMinAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentMinAmount(BigDecimal value) {
        this.paymentMinAmount = value;
    }

    /**
     * Gets the value of the originalSchool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalSchool() {
        return originalSchool;
    }

    /**
     * Sets the value of the originalSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalSchool(String value) {
        this.originalSchool = value;
    }

    /**
     * Gets the value of the recurringPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRecurringPaymentAmount() {
        return recurringPaymentAmount;
    }

    /**
     * Sets the value of the recurringPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRecurringPaymentAmount(BigDecimal value) {
        this.recurringPaymentAmount = value;
    }

    /**
     * Gets the value of the lender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLender() {
        return lender;
    }

    /**
     * Sets the value of the lender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLender(String value) {
        this.lender = value;
    }

    /**
     * Gets the value of the endingBalanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndingBalanceAmount() {
        return endingBalanceAmount;
    }

    /**
     * Sets the value of the endingBalanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndingBalanceAmount(BigDecimal value) {
        this.endingBalanceAmount = value;
    }

    /**
     * Gets the value of the availableBalanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAvailableBalanceAmount() {
        return availableBalanceAmount;
    }

    /**
     * Sets the value of the availableBalanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAvailableBalanceAmount(BigDecimal value) {
        this.availableBalanceAmount = value;
    }

    /**
     * Gets the value of the loanTermType property.
     * 
     * @return
     *     possible object is
     *     {@link LoanTermType }
     *     
     */
    public LoanTermType getLoanTermType() {
        return loanTermType;
    }

    /**
     * Sets the value of the loanTermType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanTermType }
     *     
     */
    public void setLoanTermType(LoanTermType value) {
        this.loanTermType = value;
    }

    /**
     * Gets the value of the noOfPayments property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNoOfPayments() {
        return noOfPayments;
    }

    /**
     * Sets the value of the noOfPayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNoOfPayments(Integer value) {
        this.noOfPayments = value;
    }

    /**
     * Gets the value of the balloonAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBalloonAmount() {
        return balloonAmount;
    }

    /**
     * Sets the value of the balloonAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBalloonAmount(BigDecimal value) {
        this.balloonAmount = value;
    }

    /**
     * Gets the value of the projectedInterest property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProjectedInterest() {
        return projectedInterest;
    }

    /**
     * Sets the value of the projectedInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProjectedInterest(BigDecimal value) {
        this.projectedInterest = value;
    }

    /**
     * Gets the value of the interestPaidLtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestPaidLtd() {
        return interestPaidLtd;
    }

    /**
     * Sets the value of the interestPaidLtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestPaidLtd(BigDecimal value) {
        this.interestPaidLtd = value;
    }

    /**
     * Gets the value of the interestRateType property.
     * 
     * @return
     *     possible object is
     *     {@link RateType }
     *     
     */
    public RateType getInterestRateType() {
        return interestRateType;
    }

    /**
     * Sets the value of the interestRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateType }
     *     
     */
    public void setInterestRateType(RateType value) {
        this.interestRateType = value;
    }

    /**
     * Gets the value of the loanPaymentType property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentType }
     *     
     */
    public PaymentType getLoanPaymentType() {
        return loanPaymentType;
    }

    /**
     * Sets the value of the loanPaymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentType }
     *     
     */
    public void setLoanPaymentType(PaymentType value) {
        this.loanPaymentType = value;
    }

    /**
     * Gets the value of the remainingPayments property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRemainingPayments() {
        return remainingPayments;
    }

    /**
     * Sets the value of the remainingPayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRemainingPayments(Integer value) {
        this.remainingPayments = value;
    }

}
