//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 03:39:51 PM CDT 
//


package com.nibbledebt.intuit.cad.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoanType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoanType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LOAN"/>
 *     &lt;enumeration value="AUTO"/>
 *     &lt;enumeration value="COMMERCIAL"/>
 *     &lt;enumeration value="CONSTR"/>
 *     &lt;enumeration value="CONSUMER"/>
 *     &lt;enumeration value="HOMEEQUITY"/>
 *     &lt;enumeration value="MILITARY"/>
 *     &lt;enumeration value="MORTGAGE"/>
 *     &lt;enumeration value="SMB"/>
 *     &lt;enumeration value="STUDENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LoanType", namespace = "http://schema.intuit.com/platform/fdatafeed/loanaccount/v1")
@XmlEnum
public enum LoanType {

    LOAN,
    AUTO,
    COMMERCIAL,
    CONSTR,
    CONSUMER,
    HOMEEQUITY,
    MILITARY,
    MORTGAGE,
    SMB,
    STUDENT;

    public String value() {
        return name();
    }

    public static LoanType fromValue(String v) {
        return valueOf(v);
    }

}
