//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 03:40:27 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.intuit.com/platform/fdatafeed/common/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nibbledebt.intuit.cad.data;
