//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 03:39:51 PM CDT 
//


package com.nibbledebt.intuit.cad.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.intuit.com/platform/fdatafeed/account/v1}Account">
 *       &lt;sequence>
 *         &lt;element name="postedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="programType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originalBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="currentBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="rewardQualifyAmountYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="rewardLifetimeEarned" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="segmentYtd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "postedDate",
    "programType",
    "originalBalance",
    "currentBalance",
    "rewardQualifyAmountYtd",
    "rewardLifetimeEarned",
    "segmentYtd"
})
@XmlRootElement(name = "RewardsAccount", namespace = "http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1")
public class RewardsAccount
    extends Account
{

    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar postedDate;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1")
    protected String programType;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1")
    protected BigDecimal originalBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1")
    protected BigDecimal currentBalance;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1")
    protected BigDecimal rewardQualifyAmountYtd;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1")
    protected BigDecimal rewardLifetimeEarned;
    @XmlElement(namespace = "http://schema.intuit.com/platform/fdatafeed/rewardsaccount/v1")
    protected BigDecimal segmentYtd;

    /**
     * Gets the value of the postedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostedDate() {
        return postedDate;
    }

    /**
     * Sets the value of the postedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPostedDate(XMLGregorianCalendar value) {
        this.postedDate = value;
    }

    /**
     * Gets the value of the programType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramType() {
        return programType;
    }

    /**
     * Sets the value of the programType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramType(String value) {
        this.programType = value;
    }

    /**
     * Gets the value of the originalBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOriginalBalance() {
        return originalBalance;
    }

    /**
     * Sets the value of the originalBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOriginalBalance(BigDecimal value) {
        this.originalBalance = value;
    }

    /**
     * Gets the value of the currentBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentBalance() {
        return currentBalance;
    }

    /**
     * Sets the value of the currentBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentBalance(BigDecimal value) {
        this.currentBalance = value;
    }

    /**
     * Gets the value of the rewardQualifyAmountYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRewardQualifyAmountYtd() {
        return rewardQualifyAmountYtd;
    }

    /**
     * Sets the value of the rewardQualifyAmountYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRewardQualifyAmountYtd(BigDecimal value) {
        this.rewardQualifyAmountYtd = value;
    }

    /**
     * Gets the value of the rewardLifetimeEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRewardLifetimeEarned() {
        return rewardLifetimeEarned;
    }

    /**
     * Sets the value of the rewardLifetimeEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRewardLifetimeEarned(BigDecimal value) {
        this.rewardLifetimeEarned = value;
    }

    /**
     * Gets the value of the segmentYtd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSegmentYtd() {
        return segmentYtd;
    }

    /**
     * Sets the value of the segmentYtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSegmentYtd(BigDecimal value) {
        this.segmentYtd = value;
    }

}
